/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:4487c2ebe1fca416cc30beb9e278337d:30c42bde67d45c8f4e5190bb531eeb1b:27d1f381082380631af3cd7ca71164ef$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Helix
	{
		public const string H0000 = "h0000";
		public const string H0001 = "h0001";
		public const string H0002 = "h0002";
		public const string H0003 = "h0003";
		public const string H0004 = "h0004";
		public const string H0005 = "h0005";
		public const string H0006 = "h0006";
		public const string H0007 = "h0007";
		public const string H0008 = "h0008";
		public const string H0009 = "h0009";
		public const string H0010 = "h0010";
		public const string H0011 = "h0011";
		public const string H0012 = "h0012";
		public const string H0013 = "h0013";
		public const string H0014 = "h0014";
		public const string H0015 = "h0015";
	}
}